name: "autobuild"

on:
  push:
    branches:
      - trunk

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ./build.sh
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: dist/*
      - name: Create page
        run: |
          cd www
          npm i
          node build.js
          rm -rf node_modules
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'www'
  deploy:
    name: Deploy pages

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy pages
        uses: actions/deploy-pages@v1.2.1
